### ISSUE TITLE
Bigger Buttons :)

### ISSUE THREAD

**Issue by B1adedriver** [imustafin/pbdoom#3]
Could you make the movement buttons/every button bigger? It's kind of hard to press them on a 6" screen.
Thx for the cool update!!!

**Comment by imustafin** [comment]
Hi, thanks for staying with the project!

Good idea. I will do it in the coming days.

**Comment by imustafin** [comment]
I think we can use device's DPI to make button sizes more consistent across different devices. I don't have a small device at hand, so I can't really check how it feels.

Please check https://github.com/imustafin/pbdoom/suites/10833866343/artifacts/545585508 (from https://github.com/imustafin/pbdoom/actions/runs/4116115177).

The buttons should get bigger. We can also move them around so that it is easier to touch them.

Just in case, please don't close this issue. If everything is ok, I want to do some things before closing it (I will merge the update into the main branch).

What do you think? Are buttons ok now?

**Comment by imustafin** [comment]
I have made a release with these changes https://github.com/imustafin/pbdoom/releases/tag/v0.0.3. With less buttons on screen we might increase the button sizes even more, if needed.

If the buttons are still too small, feel free to reopen this issue :)
