### ISSUE TITLE
Gameplay window size and button placement

### ISSUE THREAD

**Issue by B1adedriver** [imustafin/pbdoom#4]
Hi again, thank you for updating the project with my requests. 
I love the larger buttons and only useful buttons being shown, makes the game much easier to play on my device.

The only things that seem like an issue to me now is the gameplay window size, and the buttons being centered, rather than on the edges, of the screen.

![scr0003](https://user-images.githubusercontent.com/87837380/218575809-55b26164-6ea7-409f-9f89-5128040362de.png)
![scr0004](https://user-images.githubusercontent.com/87837380/218575899-c04d8a4f-e4c1-449e-ab9e-0f2af092d042.png)

**Comment by imustafin** [comment]
I did some tweaks for 6" displays. Can you please try https://github.com/imustafin/pbdoom/suites/11003199894/artifacts/558003323 (from https://github.com/imustafin/pbdoom/actions/runs/4186619299).

I also added digit buttons so that we can switch weapons and to see how much buttons we can fit on the screen.

A bit off-topic: most probably we need strafing (to move sideways). This could be achieved with separate strafe buttons (where to place them?) or maybe some other control scheme entirely. Do you have any suggestions? If so, you can open another issue so that we can discuss this further. Your input would be very valuable since I do not have a 6" device.

**Comment by imustafin** [comment]
I went ahead and made a release with these changes. If there is anything else we can do to improve the game, you are very welcome to open another issue. Thanks!
